### ISSUE TITLE
Configure non-default password on devices

### ISSUE THREAD

**Issue by mitar** [bsc-networks/mesh#13]
We should do that. Maybe just use the same one as for the network itself.

**Comment by CdavM** [comment]
I changed them to something else. I'll let you know of the new password in person.

**Comment by mitar** [comment]
Oh, just configure them to the SSID password. I do not think we should complicate here too much. Just so that it is not completely open for somebody to break something.

**Comment by mitar** [comment]
On north side passwords still have to be changed.

**Comment by CdavM** [comment]
South side passwords changed to the SSID one.

**Comment by mitar** [comment]
Done on north side as well.
