### ISSUE TITLE
Field Trip to Internet Archive, 2/12

### ISSUE THREAD

**Issue by CdavM** [bsc-networks/mesh#21]
Hi everyone!

I'm going to the Internet Archive next Friday to have lunch with them. Lunch starts at noon. Everyone's invited to join me on the adventure! Oh, if anyone can arrange a ride there I'd be very grateful.

**Comment by CdavM** [comment]
@mitar: maybe @sunnysideofthescreen or @jmrtns want to come? can you poke them :)

**Comment by ck2qsuZT** [comment]
I has car and want to go

**Comment by mitar** [comment]
I would also like to invite Graham. Should we also send it to bsc-hackers and hackers@cloyne mailing lists?

**Comment by mitar** [comment]
Can you prepare a message I would send?

**Comment by CdavM** [comment]
yes invite everyone!!

message subject: Field trip to Internet Archive on 2/12

Hi everyone,

I'm planning to go to the Internet Archive (SF) next Friday for lunch. It's a non-profit that is trying to archive human knowledge in all its forms. If anyone is interested in coming with me, let me know and get your inner geek out! It could be fun to see where a backup copy of the Internet is stored. We have to be there by noon.

**Comment by mitar** [comment]
Sent.

I do not have time tomorrow.

**Comment by CdavM** [comment]
That's ok because this is happening next week :)

**Comment by mitar** [comment]
Oh. :-) Good. :-)
