### ISSUE TITLE
Updaye README with euclid antenas

### ISSUE THREAD

**Issue by ck2qsuZT** [bsc-networks/mesh#23]
I need to change the IP of the Euclid-Cloyne station to 10.20.59.210 to follow the standard a bit more and then I need to find then add the MACs for the Euclid CZ link. This will have to be after I have access to the antennas which I currently do not.

**Comment by mitar** [comment]
Why you do not have access to antennas? They should be up on your side, they are just not connected to the switch.

**Comment by mitar** [comment]
Hm, maybe this is just a typo in documentation? Are you sure it is not already configured?

And yes, please add Euclid-CZ.

**Comment by ck2qsuZT** [comment]
I currently can't access our CZ antenna because some services depend on it and it's beyond our firewall. I was hoping to access everything in one go after the mesh routers are configured instead of plugging cables around and messing with VLANs

**Comment by clonm** [comment]
This has been updated
