### ISSUE TITLE
Renumber Wilde network

### ISSUE THREAD

**Issue by mitar** [bsc-networks/mesh#5]
According to the IP pool.

**Comment by CdavM** [comment]
Our router (Netgear CG3000DCR) does not support a larger subnet.  
Our equipment:
Main switches: Cisco SG-102-24-NA (1gigabit; unmanaged)
Backup switches: Dell Powerconnect 2224 (100mbit; unmanaged)

Current settings: 
Subnet mask: 255.255.255.0
DHCP Gateway IP: 10.20.12.1
DHCP start IP: 10.20.12.10
DHCP end IP: 10.20.12.199

**Comment by mitar** [comment]
We moved the IP pool. We have to renumber again.

**Comment by CdavM** [comment]
Our equipment:
Main switches: Cisco SG-102-24-NA (1gigabit; unmanaged)
Backup switches: Dell Powerconnect 2224 (100mbit; unmanaged)
Router: Netgear CG3000DCR

Current settings:
Subnet mask: 255.255.255.0 (router does not support larger subnet)
Gateway IP: 10.20.152.1
DHCP start IP: 10.20.152.10
DHCP end IP: 10.20.152.199
