### ISSUE TITLE
Configure static IP on the Loth-Wilde antenna

### ISSUE THREAD

**Issue by mitar** [bsc-networks/mesh#7]
I propose `10.20.19.210`.

Document it here: https://github.com/bsc-networks/mesh/blob/master/README.md

See Cloyne-Kingman configuration:

![nanobeamm5_300 _-_network_-_2015-02-22_14 21 38](https://cloud.githubusercontent.com/assets/585279/6996331/a8e5f83a-db36-11e4-93e7-fe5d5869ac21.png)

**Comment by CdavM** [comment]
Moved to 10.20.19.210
![loth-wilde](https://cloud.githubusercontent.com/assets/5568048/7001174/4e9763e8-dbe8-11e4-9c11-108016a23254.png)

**Comment by mitar** [comment]
We moved the IP pool. We have to renumber again.
