### ISSUE TITLE
Configure static IP on the Wilde-Loth antenna

### ISSUE THREAD

**Issue by mitar** [bsc-networks/mesh#8]
I propose `10.20.15.210`.

Document it here: https://github.com/bsc-networks/mesh/blob/master/README.md

See Cloyne-Kingman configuration:

![nanobeamm5_300 _-_network_-_2015-02-22_14 21 38](https://cloud.githubusercontent.com/assets/585279/6996333/d18a92aa-db36-11e4-8b66-fd4a3f6b3d7c.png)

**Comment by CdavM** [comment]
Assigned it to 10.20.15.210
![wilde-loth](https://cloud.githubusercontent.com/assets/5568048/7001115/188bdc76-dbe7-11e4-9617-790ccf9199b5.png)

**Comment by mitar** [comment]
We moved the IP pool. We have to renumber again.

**Comment by CdavM** [comment]
Hm. I can't connect to the antenna anymore. I was able to connect to it when I set it up, but I don't know what happened in the meantime. I tried connecting directly to it (setting my IP to 10.20.15.209; gateway, dns and subnet the same as in the antenna settings), but I still couldn't reach it. Any suggestions?

**Comment by mitar** [comment]
Is it on? :-)

**Comment by CdavM** [comment]
![wilde-loth1](https://cloud.githubusercontent.com/assets/5568048/7109015/17c2a424-e14a-11e4-8c09-68e8bb1a0ddc.png)
Hm, the red and the orange lights were blinking. After unplugging the cable and plugging it back in, it seemed to work. Thanks for your help! Maybe I have to redo the cable. Anyway, I successfully moved the IP.

**Comment by mitar** [comment]
Strange. But good that we have it back.
